@startuml
title Sequence Diagram for AddAnniversaryCommand

!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":AddAnniversaryCommandParser" as AACP LOGIC_COLOR
participant "<<class>> \n ParserUtils" as PU LOGIC_COLOR
participant "<<class>> \n AnniversaryParserUtils" as APU LOGIC_COLOR
participant ":AddAnniversaryCommand" as AAC LOGIC_COLOR
end box
box Model MODEL_COLOR_T1
participant ":Model" as M MODEL_COLOR
end box

[-> AACP: parse(String args)
activate AACP
AACP -> PU : parseEmployeeIdPrefix(String employeeIdPrefix)
activate PU
PU --> AACP: EmployeeId
deactivate PU
AACP -> APU: parseAnniversary(ArgumentMultimap argMultimap)
activate APU
APU --> AACP: Anniversary
deactivate APU
create AAC
AACP -> AAC : new AddAnniversaryCommand(EmployeeId employeeIdPrefix, Anniversary anniversary)
Activate AAC
return AddAnniversaryCommand
[<--AACP: AddAnniversaryCommand
deactivate AACP

[-> AAC: execute(Model model)
activate AAC
AAC -> M : getFullFilteredByEmployeeIdPrefixListFromData(EmployeeId employeeIdPrefix)
activate M
M --> AAC : List<Person>
deactivate M
AAC -> M : setPerson(Person target, Person editedEmployee)
[<--AAC : CommandResult

@enduml
