@startuml
title Sequence Diagram for DeleteAnniversaryCommand

!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":DeleteAnniversaryCommandParser" as DACP LOGIC_COLOR
participant ":DeleteAnniversaryCommand" as DAC LOGIC_COLOR
participant "<<class>> \n ParserUtil" as PU LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as M MODEL_COLOR
participant ":Person" as P MODEL_COLOR
end box

[-> DACP: parse(String args)
activate DACP
DACP -> PU: parseEmployeeIdPrefix(String employeeIdPrefix)
activate PU
PU --> DACP: EmployeeId
deactivate PU
DACP -> PU: parseIndex(String oneBasedIndex)
activate PU
PU --> DACP: Index
deactivate PU
create DAC
DACP -> DAC: new DeleteAnniversaryCommand(EmployeeId employeeIdPrefix)
Activate DAC
return DeleteAnniversaryCommand
[<-- DACP : DeleteAnniversaryCommand
deactivate DACP

[-> DAC: execute(Model model)
activate DAC
DAC -> M : getFullFilteredByEmployeeIdPrefixListFromData(EmployeeId employeeIdPrefix)
activate M
M --> DAC : List<Person>
deactivate M
DAC -> P : getAnniversaryList()
activate P
P --> DAC : List<Anniversary>
deactivate P
DAC -> M : setPerson(Person target, Person editedEmployee)
[<--DAC : CommandResult
deactivate DAC
@enduml
