@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant "e:EditCommand" as EditCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("edit 1 n/NewName")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("edit 1 n/NewName")
activate AddressBookParser

create EditCommandParser
AddressBookParser -> EditCommandParser
activate EditCommandParser

EditCommandParser --> AddressBookParser
deactivate EditCommandParser

AddressBookParser -> EditCommandParser : parse("1 n/NewName")
activate EditCommandParser

create EditCommand
EditCommandParser -> EditCommand
activate EditCommand

EditCommand --> EditCommandParser :
deactivate EditCommand

EditCommandParser --> AddressBookParser : e
deactivate EditCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditCommandParser -[hidden]-> AddressBookParser
destroy EditCommandParser

AddressBookParser --> LogicManager : e
deactivate AddressBookParser

LogicManager -> EditCommand : execute(m)
activate EditCommand

EditCommand -> Model : getFullFilteredByEmployeeIdPrefixListFromData(employeeIdPrefix)
activate Model

Model --> EditCommand
deactivate Model

EditCommand -> Model : commitChanges()
activate Model

Model --> EditCommand
deactivate Model

EditCommand -> EditCommand : createEditedEmployee(employeeToEdit, editEmployeeDescriptor)
activate EditCommand
deactivate EditCommand

EditCommand -> Model : setEmployee(employeeToEdit, editedEmployee)
activate Model

Model --> EditCommand
deactivate Model

EditCommand -> Model : updateFilteredEmployeeList(PREDICATE_SHOW_ALL_EMPLOYEES)
activate Model

Model --> EditCommand
deactivate Model

create CommandResult
EditCommand -> CommandResult
activate CommandResult

CommandResult --> EditCommand
deactivate CommandResult

EditCommand --> LogicManager : r
deactivate EditCommand

[<--LogicManager
deactivate LogicManager
@enduml
